spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver


mvc:
    pathmatch:
        matching-strategy: ANT_PATH_MATCHER



    jpa:
        properties:
            hibernate:
                hbm2ddl.auto: create
                transaction:
                    coordinator_class: jdbc



